version: '3.1'

services:
  db:
    user: $UID
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: pgUser
      POSTGRES_PASSWORD: pgPass
      POSTGRES_DB: pgDb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
      - ./api/src/sql/docker_pg_init.sql:/docker-entrypoint-initdb.d/docker_pg_init.sql
    ports:
      - '5432:5432'

  cache:
    image: redis:6-alpine
    command: ['--requirepass "redisPass"']
    ports:
      - '6379:6379'